Remove shvm_die function

diff --git a/bin/shvm-install b/bin/shvm-install
--- a/bin/shvm-install
+++ b/bin/shvm-install
@@ -1,6 +1,11 @@
 #!/bin/sh
 set -e
 
+abort() {
+  echo "$@" >&2
+  exit 1
+}
+
 install() {
   if [ -d "$SHVM_HOME/usr/bash-${bash_version}" ]; then
     echo "bash-${bash_version} installed"
@@ -15,13 +20,13 @@ install() {
     echo "Checking build system..."
     "$SHVM_HOME/src/bash-${bash_version}/configure" \
       --prefix="$SHVM_HOME/usr/bash-${bash_version}" 2>/dev/tty >/dev/null \
-      || shvm_die "Failed to configure bash-${bash_version}.
+      || abort "Failed to configure bash-${bash_version}.
   Make sure that '$SHVM_HOME/src/bash-${bash_version} --prefix=$SHVM_HOME/usr/bash-${bash_version}' \
   succeeds before install"
 
     echo "Building bash-${bash_version}..."
     make -C "$builddir" install >/dev/null 2>&1 \
-      || shvm_die "Failed to build bash-${bash_version}.
+      || abort "Failed to build bash-${bash_version}.
 Make sure that 'make -C $builddir install' succeeds before install"
   )
 
@@ -42,7 +47,8 @@ while test $# != 0; do
     exit 0
     ;;
   -*|--*)
-    shvm_die "Unrecognized option: $1"
+    echo >&2 "Unrecognized option: $1"
+    exit 1
     ;;
   *)
     bash_version="${1#bash-}"
