Fix build

diff --git a/usr/shvm-core/shvm-install b/usr/shvm-core/shvm-install
--- a/usr/shvm-core/shvm-install
+++ b/usr/shvm-core/shvm-install
@@ -7,10 +7,10 @@ abort() {
 }
 
 help() {
-  echo "Usage: shvm install <version>"
+  echo "Usage: shvm install <target>"
 }
 
-bash_version=
+target=
 
 while test $# != 0; do
   case "$1" in
@@ -23,40 +23,40 @@ while test $# != 0; do
     exit 1
     ;;
   *)
-    bash_version="${1#bash-}"
+    target="$1"
     ;;
   esac
   shift
 done
 
-if [ -z "$bash_version" ]; then
+if [ -z "$target" ]; then
   help
   exit 1
 fi
 
-if [ -d "$SHVM_HOME/usr/bash-${bash_version}" ]; then
-  echo "bash-${bash_version} installed"
+if [ -d "$SHVM_HOME/usr/$target" ]; then
+  echo "$target installed"
   return 0
 fi
 
-$SHVM_HOME/usr/shvm-core/shvm-fetch "$bash_version" || exit 1
+$SHVM_HOME/usr/shvm-core/shvm-fetch "$target" || exit 1
 
 builddir=$(mktemp -d)
 ( cd "$builddir"
 
   echo "Checking build system..."
-  "$SHVM_HOME/src/bash-${bash_version}/configure" \
-    --prefix="$SHVM_HOME/usr/bash-${bash_version}" 2>/dev/tty >/dev/null \
-    || abort "Failed to configure bash-${bash_version}.
-Make sure that '$SHVM_HOME/src/bash-${bash_version} --prefix=$SHVM_HOME/usr/bash-${bash_version}' \
+  "$SHVM_HOME/src/$target/configure" \
+    --prefix="$SHVM_HOME/usr/$target" 2>/dev/tty >/dev/null \
+    || abort "Failed to configure $target}.
+Make sure that '$SHVM_HOME/src/$target --prefix=$SHVM_HOME/usr/$target' \
 succeeds before install"
 
-  echo "Building bash-${bash_version}..."
+  echo "Building ${target}..."
   make -C "$builddir" install >/dev/null 2>&1 \
-    || abort "Failed to build bash-${bash_version}.
+    || abort "Failed to build ${target}.
 Make sure that 'make -C $builddir install' succeeds before install"
 )
 
 rm -rf "$builddir"
-echo "bash-${bash_version} installed"
+echo "$target installed"
 
